#!/bin/bash

# Functions for running Subversion

: ${SVN=$VCS}

function vcs_checkout_cmd() { echo $SVN co --ignore-externals $1 $2; }

function vcs_cleanup_cmd() { echo $SVN cleanup $1; }

function vcs_update_cmd() { echo $SVN up --ignore-externals $1; }

function vcs_revert_cmd() { echo $SVN revert -R $1; }

function vcs_local_head() {
  $SVN info $1 | grep Rev: | grep -o '[0-9].*$' 2>&1;
}

function vcs_latest_revision() {
  $SVN info $1 | grep Revision: | grep -o '[0-9].*$' 2>&1;
}

function vcs_first_revision() { echo '0'; }

function vcs_diff_summarize() { $SVN diff -r $1:$2 --summarize 2>&1; }
