#!/bin/bash

# Functions for running Git

: ${GIT=$VCS}

function vcs_cmd() {
  # partial cmd line for working inside of a repo without changing cwd
  # takes repo top level dir as argument
  echo $GIT --git-dir=$1/.git --work-tree=$1 --no-pager;
}

function vcs_checkout_cmd() { echo $GIT clone $1 $2; }

function vcs_cleanup_cmd() { echo $(vcs_cmd $1) clean -fdx; }

function vcs_update_cmd() { echo vcs_update $1; }
function vcs_update() {
  vcs_update_orig_wd=$(pwd)
  cd $1
  $GIT pull origin master || return 1
  $GIT submodule update --init || return 2
  cd $vcs_update_orig_wd
}

function vcs_revert_cmd() { echo $(vcs_cmd $1) reset --hard origin/master; }

function vcs_local_head() {
  $(vcs_cmd $1) rev-parse HEAD;
}

function vcs_latest_revision() {
  $(vcs_cmd $1) ls-remote origin HEAD | head -1 | awk '{print $1}';
}

function vcs_first_revision() {
  $(vcs_cmd $1) log --reverse --format=%H | head -1;
}

function vcs_diff_summarize() {
  $GIT diff --relative --name-status ${1}..${2} 2>&1;
}
